"""
Django settings for marche_tn project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from decimal import Decimal
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'boutique',
    'dashboard',
    'comptes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'marche_tn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'boutique.context_processors.types_categories',
                'boutique.context_processors.moyens_paiement_global',
                'boutique.context_processors.version_statique',
                'comptes.context_processors.commandes_a_valider',
                'comptes.context_processors.oauth_disponibles',
                'comptes.context_processors.sms_mode_test',
            ],
        },
    },
]

WSGI_APPLICATION = 'marche_tn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        # Connexions persistantes : à régler à 60 en production (0 = désactivé, recommandé avec « runserver »)
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=0, cast=int),
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {'connect_timeout': 5},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Tunis'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Envoi de SMS (connexion client + validation de commande)
# SMS_BACKEND : "console" (affiche le SMS dans le terminal, développement) ou "twilio" (envoi réel)
SMS_BACKEND = config('SMS_BACKEND', default='console')
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_FROM = config('TWILIO_FROM', default='')


# ---------------------------------------------------------------
# Comptes clients : inscription email + connexion Google / Facebook / Apple
# (en plus de la connexion par SMS gérée par l'app "comptes")
# ---------------------------------------------------------------
SITE_ID = 1
SITE_DOMAIN = config('SITE_DOMAIN', default='127.0.0.1:8000')   # en production : votre vrai nom de domaine

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_ADAPTER = 'comptes.adapters.AccountAdapter'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = config('ACCOUNT_EMAIL_VERIFICATION', default='optional')
ACCOUNT_LOGOUT_ON_GET = False
ACCOUNT_LOGIN_BY_CODE_ENABLED = False

SOCIALACCOUNT_LOGIN_ON_GET = True      # clic direct sur le bouton, sans page de confirmation
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False


# Clés OAuth : à renseigner dans le fichier .env (voir .env.example)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APPS': [{
            'client_id': config('GOOGLE_CLIENT_ID', default=''),
            'secret': config('GOOGLE_CLIENT_SECRET', default=''),
            'key': '',
        }],
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'APPS': [{
            'client_id': config('FACEBOOK_APP_ID', default=''),
            'secret': config('FACEBOOK_APP_SECRET', default=''),
            'key': '',
        }],
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
    },
    'apple': {
        'APPS': [{
            'client_id': config('APPLE_CLIENT_ID', default=''),       # Services ID
            'secret': config('APPLE_KEY_ID', default=''),             # Key ID
            'key': config('APPLE_TEAM_ID', default=''),               # Team ID / App ID Prefix
            'settings': {
                'certificate_key': config('APPLE_PRIVATE_KEY', default='').replace('\\n', '\n'),
            },
        }],
    },
}

# ---------------------------------------------------------------
# Programme de fidélité (modifiable dans .env)
# ---------------------------------------------------------------
FIDELITE_POINTS_PAR_DT = config('FIDELITE_POINTS_PAR_DT', default='1', cast=Decimal)      # points gagnés par dinar payé
FIDELITE_VALEUR_POINT = config('FIDELITE_VALEUR_POINT', default='0.020', cast=Decimal)    # 1 point = 0,020 DT (100 points = 2 DT)
FIDELITE_MIN_POINTS = config('FIDELITE_MIN_POINTS', default=100, cast=int)               # solde minimum pour utiliser ses points
FIDELITE_MAX_POURCENT = config('FIDELITE_MAX_POURCENT', default=50, cast=int)            # part max d'une commande payable en points

# ---------------------------------------------------------------
# Paiement en ligne (voir GUIDE_PAIEMENT_FIDELITE.md)
# ---------------------------------------------------------------
# Adresse publique du site, utilisée pour les retours de paiement. En production : https://monsite.tn
SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000').rstrip('/')
PAIEMENT_TIMEOUT = 15   # secondes

KONNECT_API_KEY = config('KONNECT_API_KEY', default='')
KONNECT_WALLET_ID = config('KONNECT_WALLET_ID', default='')
KONNECT_ENV = config('KONNECT_ENV', default='sandbox')       # "sandbox" (test) ou "production"

FLOUCI_PUBLIC_KEY = config('FLOUCI_PUBLIC_KEY', default='')
FLOUCI_PRIVATE_KEY = config('FLOUCI_PRIVATE_KEY', default='')

# ---------------------------------------------------------------
# Performance et robustesse : cache Redis + tâches de fond Celery (voir GUIDE_PERFORMANCE.md)
# Sans REDIS_URL, tout fonctionne comme avant (cache en mémoire, envois immédiats) : aucun Redis à installer pour développer.
# ---------------------------------------------------------------
REDIS_URL = config('REDIS_URL', default='')                       # ex : redis://127.0.0.1:6379/0
CACHE_VERSION = config('CACHE_VERSION', default=1, cast=int)      # à augmenter après un déploiement qui modifie les modèles
CACHE_TTL_CATALOGUE = config('CACHE_TTL_CATALOGUE', default=300, cast=int)

if REDIS_URL:
    CACHES = {'default': {
        'BACKEND': 'boutique.cache_backend.RedisCacheTolerant',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': '9offty',
        'VERSION': CACHE_VERSION,
        'OPTIONS': {'socket_connect_timeout': 1, 'socket_timeout': 2},
    }}
else:
    CACHES = {'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': '9offty',
        'VERSION': CACHE_VERSION,
    }}

_FILE_ATTENTE = config('CELERY_BROKER_URL', default='') or REDIS_URL
CELERY_BROKER_URL = _FILE_ATTENTE or 'memory://'
CELERY_TASK_ALWAYS_EAGER = config('CELERY_EAGER', default=not _FILE_ATTENTE, cast=bool)   # True = exécution immédiate
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_ACKS_LATE = True                 # une tâche n'est retirée de la file qu'une fois terminée
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {'socket_connect_timeout': 2, 'visibility_timeout': 3600}
CELERY_TIMEZONE = TIME_ZONE

# Emails : EMAIL_BACKEND (.env) désigne le VRAI mode d'envoi (console, SMTP...). Quand la file d'attente est active,
# Django passe par un relais qui confie l'envoi à Celery.
EMAIL_BACKEND_REEL = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_BACKEND = EMAIL_BACKEND_REEL if CELERY_TASK_ALWAYS_EAGER else 'comptes.emailing.EmailAsyncBackend'
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='webmaster@localhost')

# Authentification - espace administrateur (dashboard)
LOGIN_URL = 'dashboard:login'
LOGIN_REDIRECT_URL = 'dashboard:accueil'
LOGOUT_REDIRECT_URL = 'dashboard:login'