# Generated by Django 6.1.1 on 2026-09-28 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0003_commande_client_commande_date_validation_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(db_index=True, max_length=20)),
                ('objet', models.CharField(choices=[('connexion', 'Connexion'), ('commande', 'Validation de commande')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('utilise', models.BooleanField(default=False)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_sms', to='boutique.commande')),
            ],
            options={
                'verbose_name': 'Code SMS',
                'verbose_name_plural': 'Codes SMS',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ProfilClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(help_text='Format international : +216XXXXXXXX', max_length=20, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
        ),
    ]
