# Generated by Django 6.1.1 on 2026-09-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, help_text="Titre optionnel affiché sur l'image", max_length=150)),
                ('image', models.ImageField(upload_to='accueil_slides/')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le diaporama")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Image d'accueil",
                'verbose_name_plural': "Images d'accueil",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MoyenPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Visa, D17, BH Bank, Mastercard...', max_length=80)),
                ('logo', models.ImageField(upload_to='paiements/')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (plus petit = plus à gauche)")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moyen de paiement',
                'verbose_name_plural': 'Moyens de paiement',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterField(
            model_name='categorie',
            name='type_produit',
            field=models.CharField(choices=[('legume', 'Légume'), ('fruit', 'Fruit'), ('poisson', 'Poisson'), ('viande', 'Viande'), ('produit_laitier', 'Produit laitier'), ('epicerie', 'Épicerie'), ('autre', 'Autre')], default='legume', max_length=20),
        ),
    ]
