# Generated by Django 6.1.1 on 2026-09-28 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_imageaccueil_moyenpaiement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_validation_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='validee_par_client',
            field=models.BooleanField(default=False, help_text='Le client a saisi le code reçu par SMS'),
        ),
    ]
