# Generated by Django 6.1.1 on 2026-10-05 09:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_commande_client_commande_date_validation_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex : BIENVENUE10 (majuscules automatiques)', max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type_remise', models.CharField(choices=[('pourcentage', 'Pourcentage (%)'), ('montant', 'Montant fixe (DT)')], default='pourcentage', max_length=12)),
                ('valeur', models.DecimalField(decimal_places=3, help_text='10 = 10 % ou 10 DT selon le type', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('montant_minimum', models.DecimalField(decimal_places=3, default=0, help_text='Achat minimum (en DT) pour utiliser le code. 0 = aucun.', max_digits=8)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('utilisations_max', models.PositiveIntegerField(blank=True, help_text="Nombre total d'utilisations. Vide = illimité.", null=True)),
                ('utilisations_par_client', models.PositiveIntegerField(blank=True, default=1, help_text='Par client. Vide = illimité.', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='code_coupon',
            field=models.CharField(blank=True, help_text='Code utilisé (conservé même si le coupon est supprimé)', max_length=40),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('livraison', 'Paiement à la livraison'), ('konnect', 'En ligne (Konnect)'), ('flouci', 'En ligne (Flouci)')], default='livraison', max_length=15),
        ),
        migrations.AddField(
            model_name='commande',
            name='paye_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='points_gagnes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='points_utilises',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='reference_paiement',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='commande',
            name='remise_coupon',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='commande',
            name='remise_points',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('a_la_livraison', 'À payer à la livraison'), ('en_attente', 'Paiement en attente'), ('paye', 'Payé'), ('echoue', 'Paiement échoué'), ('rembourse', 'Remboursé')], default='a_la_livraison', max_length=15),
        ),
        migrations.AddField(
            model_name='produit',
            name='nb_avis',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
        migrations.AddField(
            model_name='commande',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='boutique.coupon'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True, max_length=1000)),
                ('visible', models.BooleanField(default=True, help_text='Décochez pour masquer cet avis sur le site')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='boutique.produit')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(fields=('produit', 'client'), name='un_avis_par_client_et_produit')],
            },
        ),
        migrations.CreateModel(
            name='MouvementPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positif = crédit, négatif = débit')),
                ('type', models.CharField(choices=[('gain', 'Points gagnés (commande livrée)'), ('utilisation', 'Points utilisés'), ('remboursement', 'Points rendus (commande annulée)'), ('annulation_gain', 'Points retirés (commande annulée)'), ('ajustement', 'Ajustement manuel')], max_length=20)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_points', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_points', to='boutique.commande')),
            ],
            options={
                'verbose_name': 'Mouvement de points',
                'verbose_name_plural': 'Mouvements de points',
                'ordering': ['-cree_le', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('commande__isnull', False)), fields=('commande', 'type'), name='un_mouvement_par_commande_et_type')],
            },
        ),
    ]
