# Generated by Django 6.1.1 on 2026-10-09 19:30

import boutique.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_avis_coupons_fidelite_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nom_ar',
            field=models.CharField(blank=True, help_text='Facultatif. Affiché à côté du nom français. Ex : طماطم', max_length=150, validators=[boutique.validators.valider_arabe], verbose_name='Nom en arabe'),
        ),
    ]
